### ISSUE TITLE
can i use Arduino MEGA with VGAX  ؟

### ISSUE THREAD

**Issue by doaajnada** [smaffer/vgax#11]
can i use Arduino MEGA with VGAX library to get more resoultion  ?
resoultion more than 120×60 pixel

**Comment by smaffer** [comment]
I own an Arduino MEGA but i have not yet ported VGAX to ATMEGA2560 MCU. 
The MCU has 8192 bytes of RAM so its possible to increase pixel depth (more colors) and increase the number of vertical lines.. but horizontal columns depends on the speed of the MCU.. The ATMEGA2560 is 16MHz, like ATMEGA328.. so the horizontal resolution should remain the same
