### ISSUE TITLE
Could I use naked ATMega8 instead of Arduino?

### ISSUE THREAD

**Issue by abomin** [smaffer/vgax#8]
Hello! Thank you for amazing library! My question: Is it possible to put your example code in ATMega8 ? (I have a clone of TL866 prog-r). I would like to make a simple VGA monitor tester. Could you help me?

**Comment by smaffer** [comment]
ATMEGA8 has only 1024 bytes of RAM. VGAX require al least 1800 bytes of RAM

**Comment by colesnicov** [comment]
And if you use [virtmem](https://github.com/rhelmus/virtmem) as a memory allocator for the VGAx library, then the external RAM memory could be used. Perhaps even increase the resolution :)
